/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../infra/db/database.config`; params?: Router.UnknownInputParams; } | { pathname: `/../infra/db/schema`; params?: Router.UnknownInputParams; } | { pathname: `/../infra/db/database.service`; params?: Router.UnknownInputParams; } | { pathname: `/../features/routines/data/routine.sqlite`; params?: Router.UnknownInputParams; } | { pathname: `/../features/exercises/data/exercise.sqlite`; params?: Router.UnknownInputParams; } | { pathname: `/../features/exercises/data/seed-exercises`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/validation/schemas`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/validation/index`; params?: Router.UnknownInputParams; } | { pathname: `/../infra/db/index`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/hooks/use-database`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/hooks/index`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/ui/theme/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../infra/db/database.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../infra/db/schema`; params?: Router.UnknownOutputParams; } | { pathname: `/../infra/db/database.service`; params?: Router.UnknownOutputParams; } | { pathname: `/../features/routines/data/routine.sqlite`; params?: Router.UnknownOutputParams; } | { pathname: `/../features/exercises/data/exercise.sqlite`; params?: Router.UnknownOutputParams; } | { pathname: `/../features/exercises/data/seed-exercises`; params?: Router.UnknownOutputParams; } | { pathname: `/../shared/validation/schemas`; params?: Router.UnknownOutputParams; } | { pathname: `/../shared/validation/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../infra/db/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../shared/hooks/use-database`; params?: Router.UnknownOutputParams; } | { pathname: `/../shared/hooks/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../shared/ui/theme/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../infra/db/database.config${`?${string}` | `#${string}` | ''}` | `/../infra/db/schema${`?${string}` | `#${string}` | ''}` | `/../infra/db/database.service${`?${string}` | `#${string}` | ''}` | `/../features/routines/data/routine.sqlite${`?${string}` | `#${string}` | ''}` | `/../features/exercises/data/exercise.sqlite${`?${string}` | `#${string}` | ''}` | `/../features/exercises/data/seed-exercises${`?${string}` | `#${string}` | ''}` | `/../shared/validation/schemas${`?${string}` | `#${string}` | ''}` | `/../shared/validation/index${`?${string}` | `#${string}` | ''}` | `/../infra/db/index${`?${string}` | `#${string}` | ''}` | `/../shared/hooks/use-database${`?${string}` | `#${string}` | ''}` | `/../shared/hooks/index${`?${string}` | `#${string}` | ''}` | `/../shared/ui/theme/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/library${`?${string}` | `#${string}` | ''}` | `/library${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../infra/db/database.config`; params?: Router.UnknownInputParams; } | { pathname: `/../infra/db/schema`; params?: Router.UnknownInputParams; } | { pathname: `/../infra/db/database.service`; params?: Router.UnknownInputParams; } | { pathname: `/../features/routines/data/routine.sqlite`; params?: Router.UnknownInputParams; } | { pathname: `/../features/exercises/data/exercise.sqlite`; params?: Router.UnknownInputParams; } | { pathname: `/../features/exercises/data/seed-exercises`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/validation/schemas`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/validation/index`; params?: Router.UnknownInputParams; } | { pathname: `/../infra/db/index`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/hooks/use-database`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/hooks/index`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/ui/theme/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
